services:
  postgres:
    image: postgres:15
    container_name: postgres-taskdb
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - springnet
  taskservice:
    build: .
    container_name: taskservice-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - springnet

networks:
  springnet: